ablecloud-team/ablestack-cockpit-plugin

python/pcs/README.md
=> PCS 관련 README.md 파일 생성

python/pcs/pacemaker.py
#84 
PCS resource status를 출력하는 함수를 호출할 때,
현재 상태 (starting, stopping)를 리턴 값에 출력하는 코드를 추가하였습니다.
=> PCS resource 상태 조회 기능

.vscode/settings.json, python/pcs/main.py, python/pcs/pacemaker.py
#87 
PCS 클러스터 구성 중 실패 등의 이유로 클러스터를 삭제할 필요가 있을 때,
리소스를 삭제하는 기능은 개발 되어 있지만, 클러스터를 삭제하는 기능이 없어 추가 했습니다.
=> PCS Cluster 삭제 기능 추가

python/disk/disk_action.py
#14 #34 일감 관련된 코드에 os type을 구분하기 위해 넣은 디버그 코드가 남아서 파싱이 안되는 문제가 있었습니다.
디버그 메세지를 삭제한 코드입니다.
추가로 주석도 추가하였습니다.
=> 디버그용 코드로 인해 json파싱이 안되는 문제 해결

tools/cloudinit/gencloudinit.py
#100  cloudinit cockpit service 실행 명령 추가
=> #100 cloudinit scvm의 cockpit service를 실행하는 명령추가

main.html, python/url/create_address.py, src/features/main.js
=> 리본요약UI 및 연결주소 생성 관련 버그 수정 

python/vm/create_ccvm_cloudinit.py, python/vm/create_scvm_cloudinit.py, python/vm/reset_cloud_center.py, python/vm/setup_pcs_cluster.py, src/features/cloud-center-virtual-machine.js, src/features/cloud-vm-wizard.js, src/features/main.js, src/features/storage-vm-wizard.js, tools/ablestack_common/ablestack/__init__.py
플러그인 경로를 ablestack-common, main.js에 공통선언후, pluginpath 변수를 사용해 사용할 수 있도록 변경
=> #110 스크립트 경로 변경

shell/host/bootstrap.sh, tools/ablestack_common/ablestack/__init__.py, tools/cloudinit/gencloudinit.py
bootstrap 자동화 스크립트 파일 작성 및 cloudinit iso생성시 --master 파라미터 추가
#124 pluginpath 관련 버그 수정(from ablecloud import * 시 pluginpath 를 잘못 불러오는 문제 해결)
=> #135 scvm 자동 bootstrap 파일 작성

manifest.json
#167  ablestack menu 위치 변경 (tools 그룹에서 menu 그룹으로 변경하였으며 order는 200을 지정하여 service 아래에 위치하도록 변경)
=> #167 cockpit 메뉴 순서 변경

src/features/cloud-center-virtual-machine.js
#185 클라우스센터 가상머신 상태가 err 메세지와 함게 시스템 에러 메세지 출력됨
=> 클라우드 센터 가상머신 상태 에러 메세지 수정

main.html, shell/host/bootstrap_run.sh, src/features/main.js, src/features/storage-cluster-maintenance-update.js, src/features/storage-vm-resource-update.js, src/features/storage-vm-status-update.html, src/features/storage-vm-status-update.js
=> #174 plugin에서 ceph의 bootstrap명령어를 실행 시킬수 있는 기능 추가

shell/host/scvm_bootstrap.sh
=> #196, #197 scvm bootstrap 관련 작업

main.html, python/scvm_status/scvm_status_detail.py, python/scvm_status/scvm_status_update.py, src/features/card-cloud-cluster-status.js, src/features/cloud-center-virtual-machine.js, src/features/main.js, src/features/storage-cluster-maintenance-update.js, src/features/storage-vm-resource-update.js, src/features/storage-vm-status-update.js
=> scvm 삭제시 /etc/ceph 하위 삭제, 30초 상태 조회시 sppiner 삽입 및 문구 수정 

python/ablestack_json/ablestackJson.py, python/cloudinit_status/README.md, python/cloudinit_status/cloudinit_status.py, tools/properties/ablestack.json
=> #209 bootstrap 조회 및 수정기능 개발

python/url/create_address.py, src/features/main.js
=> scvm, ccvm bootstrap 실행여부에 따른 요약리본 UI 알림메세지 출력

main.html, python/host/virshlist.py, src/features/cloud-center-virtual-machine.js
=> 클라우드센터 prefix 추가

shell/host/scvm_bootstrap.sh
#227 echo로 비활성화 되어있던 문제를 해결했습니다.
=> bootstrap 시 host추가기능 비활성화 문제 해결

src/features/main.js
=> 요약리본 UI - 상태조회 전 버튼 hide 처리

python/scvm_status/scvm_status_detail.py
ablestack 스토리지 가상머신 상태 NIC Type N/A 표기 버그 수정
#242
=> ablestack 스토리지 가상머신 상태 NIC Type N/A 표기 버그 수정

python/url/create_address.py
스토리지센터vm 연결 시 url 링크 버그 수정 반영
=> scvm-mngt ip정보 가져와 세팅
#244
=> 스토리지센터vm 연결 시 url 링크 버그

shell/host/scvm_bootstrap.sh
잘못된 공백으로 동작에 문제가 생길 수 있어 수정합니다.
=> #252 잘못된 공백라인 수정

src/features/main.js
스토리지 클러스터 상태(게이트웨이 상태 - 실행중 count추가) 수정
예시 => RBD GW 2개 실행중 / 3개 제공중(quorum : scvm-f3,scvm-f2,scvm-f1)
#247
=> 스토리지 클러스터 상태(게이트웨이 상태 - 실행중 count추가) 수정

main.html, src/common/wizard-common.js, src/features/card-cloud-cluster-status.js, src/features/main.js
#279 
배포 진행 단계에 따라 상태리본이 변경되도록 개선
=> Wall 모니터링센터구성 상태리본 표기

shell/host/scvm_bootstrap.sh, src/features/card-cloud-cluster-status.js
#282 
이 PR은 podman 버전 업데이트에 따라 변경된 스크립트를 수정한 내용입니다.
로컬 컨테이너 이미지를 실행하여야 하는데 기존 스크립트에서 정상적으로 실행이 되지 않아 변경된 명령어를 사용해야 합니다.
=> podman 버전 업데이트에 따른 명령어 변경 적용

shell/host/scvm_bootstrap.sh
#285 
이 PR은 bootstrap을 실행하였을 때 mgr ip를 management ip로 설정해 주는 코드를 추가했습니다.
HPN으로 구성되어 사용자가 대시보드에 연결할 수 없는 문제를 해결하였습니다.
=> mgr server ip 설정 스크립트 추가

shell/host/scvm_bootstrap.sh, src/features/wall-monitoring-wizard.js
#287  #288 
이 PR은 Wall 서비스 배포 시 서비스 이름이 잘못 되어 정상적으로 서비스를 실행할 수 없는 문제를 해결한 내용입니다.
blackbox_exporter -> blackbox-exporter 로 변경
node_exporter -> node-exporter 로 변경
scvm의 bootstrap 할 때 wall exporter 서비스도 같이 실행할 수 있도록 함
=> Wall 서비스 배포 시 서비스 이름이 잘못되어 정상 실행되지 않는 문제 해결

shell/host/scvm_bootstrap.sh
이 PR은 초기 설치 후 ceph 상태가 insecure 설정으로 인해 warning에서 OK가 되지 않는 문제를 해결합니다.
=> Ceph insecure FALSE 설정 추가

python/vm/setup_pcs_cluster.py
#291 
ccvm 배포후 5. 클러스터 구성 및 클라우드센터 가상머신 배포 단계에서 에러 발생
클라우드센터 배포 진행중 5. 클러스터 구성 및 클라우드센터 가상머신 배포 단계 진행중 "cloud center setup fail" 발생
확인결과 클라우드센터 VM 배포후 가상머신이 정상적으로 올라오는지 기다리는 시간이 60초로 설정 되어있는데
60초가 지난후 클라우드센터 VM이 올라올 경우 클라우드센터 VM은 정상적으로 올라오지만 배포단계에서 에러가 발생
해결 방안 : 최대 1분에서 5분까지 클라우드센터 가상머신이 정상적으로 올라오는지 기다리도록 수정
=> ccvm 배포후 5. 클러스터 구성 및 클라우드센터 가상머신 배포 단계에서 에러 발생

src/features/card-cloud-cluster-status.js, src/features/main.js, src/features/wall-monitoring-wizard.js
- Skydive 구성 소스 추가
- mold에서 skydive를 구성하고 각 agent의 skydive.yml에 명시된 값(analyzer ip값)을 수정하는 소스입니다.
- 드롭다운 메뉴에서 "스카이 다이브 연결" 링크를 추가하였습니다.
- 기타 잘못된 주석과 console 메시지등을 삭제, 편집하였습니다.
=> 1. 스카이다이브 구성 소스 추가2. 주석 변경 및 console 에러 수정

main.html, src/features/main.js, src/features/wall-monitoring-wizard.js
#295 
1. 초기 상태를 불러올때 ABLESTACK 어플라이언스 상태여부와 상관없이 무조건 "ABLESTACK 스토리지센터 및 클라우드센터 VM이 배포되지 않았습니다." 문구를 "ABLESTACK 가상어플라이언스 상태를 확인 중입니다." 로 변경
2. 배포가 완료된 후에는 리본 단계가 설치 단계로 돌아가지 못하도록 리본 표기 로직 수정
=> ABLESTACK 리본 표기 버그 수정

python/vm/setup_pcs_cluster.py, shell/host/ccvm_bootstrap.sh, shell/host/scvm_bootstrap.sh
#298 
이 PR은 HA 아키텍쳐 변경으로 인한 추가 스크립트 및 코드 입니다.
주요 작업
추가 작업
없음
=> HA 아키텍쳐 변경으로 인한 스크립트 및 코드 추가

main.html, python/vm/setup_pcs_cluster.py, shell/host/ccvm_bootstrap.sh, shell/host/scvm_bootstrap.sh, src/common/logger.js, src/common/wizard-common.js, src/features/card-cloud-cluster-status.js, src/features/cloud-center-virtual-machine.js, src/features/cloud-vm-wizard.html, src/features/cloud-vm-wizard.js, src/features/cluster-config-prepare.html, src/features/cluster-config-prepare.js, src/features/main.js, src/features/storage-cluster-maintenance-update.js, src/features/storage-vm-resource-update.js, src/features/storage-vm-status-update.js, src/features/storage-vm-wizard.html, src/features/storage-vm-wizard.js, src/features/wall-monitoring-wizard.html
GS 인증 1차 결함리포트 프로그램 결함 사항 수정 작업 진행
#299 
GS 인증 1차 결함을 수정하여 반영하였습니다.
=> GS 인증 1차 결함 수정 반영

python/host/virshedit.py, src/features/cloud-center-virtual-machine.js
gs 인증 ccvm 자원변경이 정상적으로 안되던 문제 해결
=> gs 인증 ccvm 자원변경 오류 개선

css/patternfly.css, main.html, python/host/virshedit.py, src/common/logger.js, src/common/wizard-common.js, src/features/card-cloud-cluster-status.js, src/features/cloud-center-virtual-machine.js, src/features/cloud-vm-wizard.js, src/features/cluster-config-prepare.html, src/features/cluster-config-prepare.js, src/features/main.js, src/features/storage-cluster-maintenance-update.js, src/features/storage-vm-resource-update.js, src/features/storage-vm-status-update.js, src/features/storage-vm-wizard.js, src/features/wall-monitoring-wizard.html
#307 
GS 인증 관련 결함 사항
1. 클라우드센터 vm 자원변경 시 중지 상태일때만 가능하도록 기능 수정
2. 클라우드센터 vm 자원변경 기능 ccvm.xml 오퍼링 변경시 ccvm.xml 경로 잘못 표기된 버그 수정
3. ABLESTACK 우측 메뉴 클릭 시 다른 영역 클릭하여 닫히도록 기능 수정
4. 클라우드센터 클러스트 클린업 모달창 "X" 버튼 닫기 기능 미작동 버그 수정
5. '클러스터 시작' 버튼을 '클라우드센터 VM 시작' 버튼으로 변경
6. '클러스터 중지' 버튼을 '클라우드센터 VM 정지'버튼으로 변경
7. ABLESTACK 리본 메뉴 버튼 활성화/비활성화 표시가 상태에 맞지 않게 표기되던 버그 수정
8. 브라우저 크기에 따라 화편 깨짐 현상 발생하던 부분 스크롤바로 화면 깨짐 현상 수정
9. ABLESTACK 기능 사용시 로그 기록 추가
10. 스토리지센터, 클라우드센터 배포 마법사 파일 업로드 기능 중 파일용량 100kb로 제한하는 기능 추가
=> GS 인증 관련 결함사항 반영

src/features/cluster-config-prepare.html, src/features/cluster-config-prepare.js
클러스터 구성준비 단계에서의 기능 개선(hosts, 파일준비, 시간서버)
- 호스트 파일 생성 기능 중, Alias2는 Alias1 이름과 관계없이 ablecube, ablecube-pn으로 고정하였습니다.
- 호스트가 총 6대라고 가정할 경우 - 시간서버1: ablecube-pn1, 시간서버2: ablecube-pn2, 시간서버3: ablecube-pn3 
관련 이슈 #316
=> 클러스터 구성 준비 - Hosts 파일, 시간서버 단계 기능 개선

main.html, python/ccvm_snap/ccvm_snap_action.py, python/vm/setup_pcs_cluster.py, src/features/card-cloud-cluster-status.js, src/features/cloud-center-virtual-machine.js
#320 
1. 클라우드센터 vm 스냅샷 생성기능 추가
2. ccvm 배포 시 pcs 구성 호스트에 1일 1회 ccvm 스냅샷 생성 python 실행 crontab 등록 기능 개발
=> 클라우드센터vm 스냅샷 생성기능 및 클라우드센터 가상머신 배포 시 ccvm 스냅샷 생성 crontab 등록 기능 개발

python/url/create_address.py, src/features/card-cloud-cluster-status.js, src/features/wall-monitoring-wizard.js
skydive 명칭 변경 및 접속 경로 변경으로 PR 드립니다.
=> 1. skydive 주소생성 코드 삭제 2. skydive 명칭 변경에 따른 코드 수정

manifest.json, src/common/wizard-common.js, src/features/cloud-vm-wizard.html, src/features/cloud-vm-wizard.js, src/features/cluster-config-prepare.html, src/features/cluster-config-prepare.js, src/features/storage-vm-wizard.html, src/features/storage-vm-wizard.js
=> CCVM, SCVM 배포마법사에서 개선된 호스트 파일 입력 기능 적용 및 클러스터 구성 준비 마법사에서 로컬시간서버 사용 제한 기능 추가

shell/host/ccvm_bootstrap.sh
기본 설정이 enable로 되어 있어 scvm에서도 시작되어 activating 상태로 지속되는 현상이 발견되었습니다.
기본 설정을 disable로 설정하고 ccvm bootstrap에서 enable 할 수 있도록 변경하였습니다.
이 PR은 ...
=> cloudstack usage 자동 시작 변경

src/common/wizard-common.js
=> 클러스터 구성 준비 - Hosts 파일 불러오기 버그 수정

src/common/wizard-common.js, src/features/cloud-vm-wizard.html, src/features/cluster-config-prepare.html, src/features/storage-vm-wizard.html
=> [UI변경] hosts 파일 불러오는 영역(div) 위치 변경

main.html
=> [버그] CCVM DB 백업 기능 중, 오탈자 수정

shell/host/ccvm_bootstrap.sh
이 PR은 기존 uefi.properties 파일을 host로 복사해 주어야 하는 내용이 누락되는 버그가 발생하여 수정했습니다.
ccvm bootstrap을 실행하면 ccvm 로컬에 uefi.properties 파일을 생성하고,
scp를 이용하여 각 호스트에 /etc/cloudstack/agent 디렉터리 밑에 복사하는 내용을 추가하였습니다.
=> uefi properties 파일을 bootstrap 과정에서 호스트로 전송하는 내용 추가

tools/makerpm/ablestack.spec, tools/makerpm/rpmbuild.sh
이 PR은 jenkins사용을 하거나 여러버전의 코드를 빌드하기 위해 빌드경로를 절대경로가 아닌 상대경로로 변경하는 패치입니다.
=> 빌드경로를 상대경로로 변경

src/features/storage-vm-status-update.js
scvm 배포 후 bootstrap을 실행시키면 ablestack.json의 scvm 설정정보가 true가 되는데,
scvm을 삭제시 ablestack.json의 scvm 설정정보를 수동으로 false로 초기화 해야 스토리지센터 가상머신 배포 기능이 활성화해야 함
그래서 scvm을 삭제시 ablestack.json의 scvm 설정정보를 자동으로 false 처리 하도록 기능 개선
=> scvm 삭제시 호스트의 ablestack.json의 scvm 설정 초기화 기능

tools/xml-template/ccvm-xml-template-bios.xml, tools/xml-template/ccvm-xml-template.xml, tools/xml-template/scvm-xml-template-bios.xml, tools/xml-template/scvm-xml-template.xml
기존 scvm 및 ccvm의 부팅 모드를 bios에서 uefi 모드로 변경했습니다.
qcow2 템플릿 변경에 따라 템플릿 xml 파일도 bios에서 uefi로 변경하였습니다.
기존 bios 모드의 템플릿은 *-bios*로 이름만 변경했습니다.
=> scvm,ccvm template xml 변경

python/host/virshlist.py, python/vm/create_scvm_cloudinit.py, python/vm/reset_cloud_center.py, python/vm/reset_storage_center.py, shell/host/scvm_bootstrap.sh
1. uefi vm을 제거하는 경우 nvram삭제/유지 설정이 필요하여 해당 내용 업데이트
uefi vm의 경우 nvram을 사용하는데, 해당 vm의 경우 undefine시 nvram파일의 삭제, 또는 유지를 결정해야만 합니다.
해당 내용이 없는 경우 vm의 undefine에 실패하여 scvm/ccvm의 재배포시 오류가 발생합니다.
2. jenkins빌드시 버전 관리가 필요하여 해당 내용 변경
=> uefi변경에 대응 및 jenkins 빌드를 위한 버전관리

main.html, python/ccvm_service/ccvm_service_control.py, python/host/virshlist.py, src/features/card-cloud-cluster-status.js, src/features/cloud-center-virtual-machine.js
클라우드센터 가상머신 mold 서비스 및 db 상태 체크가능하도록 기능개선
=> 클라우드센터 가상머신 mold 서비스 및 db 상태 체크가능하도록 기능개선

main.html, python/host/virshlist.py, python/scvm_status/scvm_status_detail.py, python/vm/create_ccvm_cloudinit.py, python/vm/create_scvm_cloudinit.py, src/features/cloud-center-virtual-machine.js, src/features/cloud-vm-wizard.html, src/features/cloud-vm-wizard.js, src/features/main.js, src/features/storage-vm-wizard.html, src/features/storage-vm-wizard.js, tools/cloudinit/gencloudinit.py
scvm과 ccvm의 기본 게이트웨이를 필수조건이 아닌 선택사항으로 기능을 개발
ccvm과 각 scvm에 입력하는 기본 게이트웨이에 대해 필수로 입력하지 않게 변경한 후, 선택사항으로 입력해도 되고 ,입력 하지 않아도 되는 기능으로 바꾸었습니다.
=> scvm,ccvm 기본 게이트웨이 선택사항 기능 개발

python/pcs/pacemaker.py, shell/host/ccvm_bootstrap.sh, shell/host/scvm_bootstrap.sh
이 PR은 ABLESTACK Cerato의 기능 업데이트와 관련된 내용입니다.
1. pg autoscale update
- 기존 replicated rule로 생성된 pool의 pg autoscale의 class가 설정되어 있지 않아 추후 생성되는 rbd 풀의 pg autoscale이 자동으로 설정되지 않는 기능을 수정하였습니다.
2. pcs stickiness update
- 호스트 장애 등으로 pcs 리소스가 다른 호스트로 마이그레이션 된 후 호스트가 복구 되었을 때 pcs 리소스가 원래 호스트(default host)로 다시 마이그레이션 되는 기능을 수정하였습니다.
- skickiness 설정을 하면 장애 호스트가 복구되더라도 리소스는 마이그레이션 된 호스트에서 실행된 상태를 유지합니다.
3. tpm 설정 파일 업데이트
- cloudstack-agent 디렉터리에 tpm 관련 설정 파일을 추가 하였습니다.
=> Cerato 기능 업데이트 (pcs, ceph, tpm)

main.html, python/cluster/cluster_config.py, python/cluster/cluster_hosts_setting.py, python/glue/update_glue_config.py, python/vm/create_ccvm_cloudinit.py, python/vm/create_ccvm_xml.py, python/vm/setup_storage_vm.py, src/common/wizard-common.js, src/features/card-cloud-cluster-status.js, src/features/cloud-vm-wizard.html, src/features/cloud-vm-wizard.js, src/features/cluster-config-prepare.js, src/features/main.js, src/features/storage-vm-wizard.html, src/features/storage-vm-wizard.js
ablecube 추가기능 편의성 제고를 위한 기능 개선
주요 개선사항
1. scvm, ccvm 배포시 해당 호스트의 cluster.conf 파일을 불러와서 프로파일 자동 세팅 되도록 기능개선
2. 전체 호스트 Glue 설정 업데이트 기능 개발 ( keyring, ceph.conf 파일 갱신하여 전체 호스트에 복사)
기타 수정사항
1. scvm, ccvm 배포 마법사 마지막 확인 단계 이상동작 수정
=> 호스트 추가 기능 개선

python/disk/disk_action.py, src/features/storage-vm-wizard.js
scvm 배포시 disk 정보를 /dev/disk/by-path/ 를 참조하도록 개선
=> scvm 배포시 disk 정보를 /dev/disk/by-path/ 를 참조하도록 개선

tools/xml-template/ccvm-xml-template-bios.xml, tools/xml-template/ccvm-xml-template.xml, tools/xml-template/scvm-xml-template-bios.xml, tools/xml-template/scvm-xml-template.xml
이 PR은 qemu 레거시 에뮬레이터에서 빌드된 최신 에뮬레이터로 수정한 내용입니다.
Mold를 이용하여 생성된 VM은 빌드된 최신 qemu 에뮬레이터를 사용하여 생성되지만 scvm 및 ccvm은 기존 템플릿으로 VM이 생성되는 과정에서 에뮬레이터 패치가 누락된 버그를 수정했습니다.
=> scvm, ccvm qemu emulator 수정

shell/host/scvm_bootstrap.sh, tools/xml-template/ccvm-xml-template.xml, tools/xml-template/scvm-xml-template.xml
이 PR은 SCVM, CCVM의 디스크 컨트롤러 슬롯 버그 수정 및 RBD 캐시 사이즈 변경 및 CCVM 캐시 및 io uring 설정 추가에 관련된 내용입니다.
- 디스크 컨트롤러의 슬롯 번호가 1로 되어 있어 정상적으로 VM이 생성되지 않는 버그 수정
- 슬롯 번호 0으로 변경
- RBD 캐시 사이즈 변경
- 기존 1G 에서 4G로 변경
- CCVM 캐시 및 io uring 설정
- CCVM 캐시 설정 (writeback)
- io 설정 (io_uring)
=> 디스크 컨트롤러 버그 수정 및 RBD 캐시 설정 및 CCVM 설정 변경

python/cluster/cluster_config.py, python/vm/create_ccvm_cloudinit.py, python/vm/create_ccvm_xml.py, src/common/wizard-common.js, src/features/card-cloud-cluster-status.js, src/features/cloud-vm-wizard.html, src/features/cloud-vm-wizard.js, src/features/cluster-config-prepare.html, src/features/cluster-config-prepare.js, src/features/main.js, src/features/storage-vm-status-update.js, src/features/storage-vm-wizard.html, src/features/storage-vm-wizard.js, src/features/wall-monitoring-wizard.js, tools/properties/cluster.json
1) scvm, ccvm bootstrap 실행중 문구 변경
2) 모니터링센터 구성시 ip 정보 자동 세팅 기능 추가
3) ccvm 배포 후 설정파일 백업하는 기능 수정
4) scvm, ccvm 배포시 현재 호스트의 ssh key 정보로 자동 세팅 기능 추가
5) scvm, ccvm 배포시 관리 NIC cidr, gateway, dns에 따라 자동 세팅 기능 추가
=> 2022.10.18 Cerato 통합테스트 개선요구사항 반영

python/cluster/cluster_config.py, python/cluster/cluster_hosts_setting.py, python/glue/update_glue_config.py, python/vm/create_ccvm_cloudinit.py, python/vm/create_ccvm_xml.py, python/vm/create_scvm_xml.py, python/vm/host_ping_test.py, python/vm/setup_pcs_cluster.py, python/vm/setup_storage_vm.py, shell/host/virsh_secret_key.sh, src/common/wizard-common.js, src/features/card-cloud-cluster-status.js, src/features/cloud-vm-wizard.html, src/features/cloud-vm-wizard.js, src/features/cluster-config-prepare.html, src/features/cluster-config-prepare.js, src/features/main.js, src/features/storage-vm-wizard.html
=> 2022.10.21 통합테스트 수정사항 반영

src/features/main.js
ABLESTACK Cockpit Plugin에서의 종료 절차를 자동으로 실행하는 기능 중,
볼륨 마운트에 관한 주의사항 문구를 변경하였습니다.
=> [UI]전체 시스템 종료 문구 변경

shell/host/ccvm_bootstrap.sh, shell/host/scvm_bootstrap.sh
이 PR은 기존 SCVM bootstrap에서 crush ruleset 중 replication_ruleset의 default class를 수정하는 작업을 진행한 결과 버그가 있어 CCVM bootstrap에서 실행하도록 변경하였습니다.
- 기존 : scvm bootstrap에서 crush ruleset 변경
- 변경 : ccvm bootstrap에서 crush ruleset 변경
ps. commit 중 bootstrap 단계에서 podman rpm 및 이미지를 삭제하는 것은 원복하고 qcow2 템플릿에서 bridge 이름을 수정하는 방법으로 변경하였습니다.
=> Glue crush ruleset 클래스 추가 위치 변경

python/host/virshlist.py
ccvm dns에 입력을 해도 undefined로 인식이 되어서 따옴표 문제였습니다.
변경 후 ccvm dns가 나타납니다.
=> CCVM DNS undefined로 인식 되는 오류 수정

shell/host/ccvm_bootstrap.sh
이 PR은 glue autoscale 설정을 위해 ccvm bootstrap 시점에서 실행되는 crushmap 설정에 버그를 수정했습니다.
ccvm은 스토리지 센터에 접근할 수 없어 ceph 명령어를 실행하지 못해 crushmap 설정 스크립트를 실행하지 못하는 버그가 있어 ssh를 이용하여 scvm에서 스크립트를 쉘로 실행할 수 있도록 변경하였습니다.
=> Crushmap 설정 버그 수정

src/features/cluster-config-prepare.js
이 PR은 호스트 시간 동기화 설정 파일 수정에 관련된 내용입니다.
기존 방식에서 second host로 설정된 호스트가 재부팅 되었을 때 정상적으로 시간이 동기화 되지 않는 문제가 발견되었습니다.
따라서 second host의 마스터 역할을 삭제하고 master host로 지정된 호스트의 시간서버로만 동기화 될 수 있도록 변경한 후 HA 테스트를 통해서 시간 서버의 동기화가 정상적으로 되는 것을 테스트 완료 하였습니다.
변경 된 설정으로 HA 테스트를 진행하여 시간서버 동기화가 정상적으로 되는 것을 확인했습니다.
1번 호스트를 강제 종료하면 나머지 모든 호스트는 2번 호스트에 동기화 되며, 2번 호스트를 강제 종료하면 모든 호스트는 전부 1번 호스트로 동기화 됩니다.
=> chrony 서버 시간 동기화 설정 파일 수정

src/features/cloud-vm-wizard.html, src/features/cluster-config-prepare.html, src/features/storage-vm-wizard.html
클러스터 구성 준비단계에서 클러스터 구성 프로파일 입력 테이블 높이 문제로 하단 입력란이 보이지 않는 문제 개선
=> 클러스터 구성 프로파일 입력 테이블 height 조절 (아래 입력란이 보이도록)

main.html, python/cluster/cluster_config.py, python/cluster/remove_cube_host.py, python/vm/ccvm_dup_deploy.py, shell/host/ccvm_dup_bootstrap.sh, src/features/card-cloud-cluster-status.js, src/features/cloud-vm-change.html, src/features/main.js, tools/cloudinit/gencloudinit.py
1. 클라우드센터 가상머신 이중화
2. 호스트 제거시 cluster.json, hosts 정보를 update하는 기능 개발
=> 클라우드센터 가상머신 이중화 및 호스트 제거시 cluster.json, hosts 정보를 update하는 기능 개발

src/features/main.js
각 호스트마다의 scvm,ccvm에 대한 상단 에러에 대한 해결방안 문구를 설정 완료했습니다.
이 PR은 ...
=> 각 해당 error에 대한 Alert 해결방안 문구 설정완료

shell/host/ccvm_dup_bootstrap.sh
이 PR은 CCVM 이중화를 위한 bootstrap 파일 생성에 관한 내용입니다.
이중화를 위한 CCVM(ccvm_dup)에서 Mold 관련 방화벽 포트를 허용하고 데이터베이스는 기존 구성되어 있는 서버로 연결하는 작업 등이 포함되어 있습니다.
=> ccvm 이중화를 위한 bootstrap 파일 생성

tools/xml-template/ccvm-xml-template.xml, tools/xml-template/scvm-xml-template.xml
이 PR은 SCVM, CCVM에 agent 변경으로 인한 버그가 발견되어 xml 템플릿을 수정한 내용입니다.
scvm, ccvm 템플릿 공통
=> SCVM, CCVM xml 템플릿 수정
